# -*- coding: utf-8 -*-
"""BSCNet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mdmSa9Ht93ikh11JduPNPUMOV5Od9bLK
"""

# ===== Cell 1: GPU Check + Folder Setup =====
import torch, os

print("PyTorch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

# Make folders
os.makedirs("synthetic_dataset/images", exist_ok=True)
os.makedirs("synthetic_dataset/masks", exist_ok=True)
os.makedirs("seg_project/checkpoints", exist_ok=True)

print("Project folders created!")

# ===== Cell 2: Generate Cartoon City Dataset =====
import cv2
import numpy as np
from PIL import Image
import random

IMG_W, IMG_H = 512, 256
NUM_IMAGES = 120  # you can increase to 300 later

# Class labels:
# 0 = sky
# 1 = road
# 2 = building
# 3 = tree
# 4 = car

def draw_building(img, mask):
    x1 = random.randint(0, IMG_W-150)
    x2 = x1 + random.randint(50, 150)
    y2 = random.randint(120, 230)
    y1 = random.randint(50, 150)

    color = (160,160,160)
    cv2.rectangle(img, (x1,y1), (x2,y2), color, -1)
    cv2.rectangle(mask, (x1,y1), (x2,y2), (2,), -1)

def draw_tree(img, mask):
    x = random.randint(40, IMG_W-40)
    y = random.randint(130, 220)

    # trunk
    cv2.rectangle(img, (x-5,y), (x+5,y+30), (70,40,20), -1)
    cv2.rectangle(mask, (x-5,y), (x+5,y+30), (3,), -1)

    # top
    cv2.circle(img, (x,y), 20, (0,150,0), -1)
    cv2.circle(mask, (x,y), 20, (3,), -1)

def draw_car(img, mask):
    x1 = random.randint(10, IMG_W-90)
    y1 = random.randint(180, 220)
    x2 = x1 + random.randint(40, 80)
    y2 = y1 + random.randint(20, 40)

    cv2.rectangle(img, (x1,y1), (x2,y2), (0,0,255), -1)
    cv2.rectangle(mask, (x1,y1), (x2,y2), (4,), -1)

def generate_city_image():
    img = np.zeros((IMG_H, IMG_W, 3), dtype=np.uint8)
    mask = np.zeros((IMG_H, IMG_W), dtype=np.uint8)

    # sky
    img[:] = (255,200,150)
    mask[:] = 0

    # road
    cv2.rectangle(img, (0,180), (IMG_W, IMG_H), (120,120,120), -1)
    cv2.rectangle(mask, (0,180), (IMG_W, IMG_H), (1,), -1)

    for _ in range(random.randint(1,3)):
        draw_building(img, mask)
    for _ in range(random.randint(1,3)):
        draw_tree(img, mask)
    for _ in range(random.randint(1,3)):
        draw_car(img, mask)

    return img, mask

for i in range(NUM_IMAGES):
    img, mask = generate_city_image()
    Image.fromarray(img).save(f"synthetic_dataset/images/{i:04d}.png")
    Image.fromarray(mask).save(f"synthetic_dataset/masks/{i:04d}.png")

print(f"Generated {NUM_IMAGES} simple city images!")

# ===== Cell 3: Dataset Loader =====
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from PIL import Image
import numpy as np
import torch

RESIZE = (512, 256)

class CityDataset(Dataset):
    def __init__(self, img_folder, mask_folder):
        import glob
        self.img_paths = sorted(glob.glob(img_folder + "/*.png"))
        self.mask_paths = sorted(glob.glob(mask_folder + "/*.png"))
        self.normalize = transforms.Normalize(
            mean=[0.485,0.456,0.406],
            std=[0.229,0.224,0.225]
        )

    def __len__(self): return len(self.img_paths)

    def __getitem__(self, idx):
        img = Image.open(self.img_paths[idx]).convert("RGB")
        mask = Image.open(self.mask_paths[idx])

        img = img.resize(RESIZE, Image.BILINEAR)
        mask = mask.resize(RESIZE, Image.NEAREST)

        img = transforms.ToTensor()(img)
        img = self.normalize(img)
        mask = torch.from_numpy(np.array(mask)).long()

        return img, mask

print("CityDataset ready!")

# ===== Cell 4: Train/Val Loaders =====
from torch.utils.data import random_split

full_dataset = CityDataset("synthetic_dataset/images", "synthetic_dataset/masks")

val_size = int(0.15 * len(full_dataset))
train_size = len(full_dataset) - val_size

train_ds, val_ds = random_split(full_dataset, [train_size, val_size])

train_loader = DataLoader(train_ds, batch_size=4, shuffle=True)
val_loader = DataLoader(val_ds, batch_size=1)

print("Train samples:", train_size)
print("Val samples:", val_size)

import os
print(os.listdir("synthetic_dataset/masks")[:5])

from PIL import Image
import numpy as np

mask = np.array(Image.open("synthetic_dataset/masks/0000.png"))
print("Unique mask values:", np.unique(mask))

# ===== Cell 5: TinyBSCNet (Clean Working Version) =====

import torch
import torch.nn as nn
import torch.nn.functional as F

# --------------------------------------------------
# Conv Block
# --------------------------------------------------
class ConvBlock(nn.Module):
    def __init__(self, in_ch, out_ch):
        super().__init__()
        self.block = nn.Sequential(
            nn.Conv2d(in_ch, out_ch, 3, padding=1),
            nn.BatchNorm2d(out_ch),
            nn.ReLU(inplace=True),

            nn.Conv2d(out_ch, out_ch, 3, padding=1),
            nn.BatchNorm2d(out_ch),
            nn.ReLU(inplace=True),
        )
    def forward(self, x):
        return self.block(x)


# --------------------------------------------------
# Simple BFM (Boundary Feature Module)
# --------------------------------------------------
class SimpleBFM(nn.Module):
    def __init__(self, in_ch, out_ch):
        super().__init__()
        self.conv = nn.Conv2d(in_ch, out_ch, 3, padding=1)
        self.bn   = nn.BatchNorm2d(out_ch)
        self.relu = nn.ReLU(inplace=True)

    def forward(self, x):
        return self.relu(self.bn(self.conv(x)))


# --------------------------------------------------
# Simple ELPPM (Context Pyramid)
# --------------------------------------------------
class SimpleELPPM(nn.Module):
    def __init__(self, in_ch, out_ch):
        super().__init__()

        # Pyramids
        self.p1 = nn.AdaptiveAvgPool2d(1)
        self.p2 = nn.AdaptiveAvgPool2d(2)
        self.p3 = nn.AdaptiveAvgPool2d(4)

        # Reduce channels
        self.c1 = nn.Conv2d(in_ch, out_ch, 1)
        self.c2 = nn.Conv2d(in_ch, out_ch, 1)
        self.c3 = nn.Conv2d(in_ch, out_ch, 1)

        # Fuse
        self.fuse = nn.Conv2d(out_ch * 3, out_ch, 1)

    def forward(self, x):
        h, w = x.shape[2:]

        f1 = F.interpolate(self.c1(self.p1(x)), (h, w))
        f2 = F.interpolate(self.c2(self.p2(x)), (h, w))
        f3 = F.interpolate(self.c3(self.p3(x)), (h, w))

        return self.fuse(torch.cat([f1, f2, f3], dim=1))


# --------------------------------------------------
# TinyBSCNet (encoder → elppm → decoder → bfm)
# --------------------------------------------------
class TinyBSCNet(nn.Module):
    def __init__(self, num_classes=5):
        super().__init__()

        # Encoder
        self.enc1 = ConvBlock(3,32)
        self.enc2 = ConvBlock(32,64)
        self.enc3 = ConvBlock(64,128)

        self.pool = nn.MaxPool2d(2,2)

        # Bottleneck
        self.bottleneck = ConvBlock(128,256)

        # Context (ELPPM)
        self.elppm = SimpleELPPM(256,128)

        # Decoder
        self.up3 = nn.ConvTranspose2d(128,128,2,2)
        self.dec3 = ConvBlock(128+128,128)

        self.up2 = nn.ConvTranspose2d(128,64,2,2)
        self.dec2 = ConvBlock(64+64,64)

        self.up1 = nn.ConvTranspose2d(64,32,2,2)
        self.dec1 = ConvBlock(32+32,32)

        # Boundary refinement
        self.bfm = SimpleBFM(32,32)

        # Final prediction
        self.final = nn.Conv2d(32, num_classes, 1)

    def forward(self, x):
        e1 = self.enc1(x); p1 = self.pool(e1)
        e2 = self.enc2(p1); p2 = self.pool(e2)
        e3 = self.enc3(p2); p3 = self.pool(e3)

        b = self.bottleneck(p3)
        b = self.elppm(b)

        u3 = self.up3(b)
        d3 = self.dec3(torch.cat([u3, e3], dim=1))

        u2 = self.up2(d3)
        d2 = self.dec2(torch.cat([u2, e2], dim=1))

        u1 = self.up1(d2)
        d1 = self.dec1(torch.cat([u1, e1], dim=1))

        d1 = self.bfm(d1)
        return self.final(d1)


device = "cuda"
model = TinyBSCNet(num_classes=5).to(device)
print("Model ready!")

# ===== Cell 6: Train TinyBSCNet safely =====
import torch
import torch.nn as nn
import torch.optim as optim
from torch.amp import autocast, GradScaler   # new API
import time
import json

device = "cuda"
EPOCHS = 20
LR = 3e-4

criterion = nn.CrossEntropyLoss()
optimizer = optim.AdamW(model.parameters(), lr=LR, weight_decay=1e-5)
scaler = GradScaler(device=device)

best_val_loss = 1e9
history = {"train_loss": [], "val_loss": []}

print("Starting training...\n")

for epoch in range(1, EPOCHS+1):
    model.train()
    train_loss = 0
    t0 = time.time()

    for imgs, masks in train_loader:
        imgs = imgs.to(device, non_blocking=True)
        masks = masks.to(device, non_blocking=True)

        optimizer.zero_grad()

        with autocast(device_type="cuda"):
            logits = model(imgs)
            loss = criterion(logits, masks)

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        train_loss += loss.item() * imgs.size(0)

    train_loss /= len(train_loader.dataset)

    # -------- Validation --------
    model.eval()
    val_loss = 0
    with torch.no_grad():
        for imgs, masks in val_loader:
            imgs = imgs.to(device)
            masks = masks.to(device)

            with autocast(device_type="cuda"):
                logits = model(imgs)
                loss = criterion(logits, masks)

            val_loss += loss.item() * imgs.size(0)

    val_loss /= len(val_loader.dataset)

    history["train_loss"].append(train_loss)
    history["val_loss"].append(val_loss)

    print(f"Epoch {epoch}/{EPOCHS} | Train={train_loss:.4f} | Val={val_loss:.4f} | Time={time.time()-t0:.1f}s")

    # Save best model
    if val_loss < best_val_loss:
        best_val_loss = val_loss
        torch.save(model.state_dict(), "best_model.pth")
        print(" → Saved best_model.pth")

# Save history
with open("history.json","w") as f:
    json.dump(history, f)

print("\nTraining complete!")
print("Best validation loss:", best_val_loss)

# ===== Cell 7: Show side-by-side predictions (fixed display) =====
import torch
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image

device = "cuda"

# Load best model
model.load_state_dict(torch.load("best_model.pth", map_location=device))
model.eval()

# Color map (5 classes)
colors = {
    0: (0,0,0),
    1: (0,255,0),
    2: (0,0,255),
    3: (255,0,0),
    4: (255,255,0),
}

def colorize(mask):
    h, w = mask.shape
    rgb = np.zeros((h,w,3), dtype=np.uint8)
    for cls, c in colors.items():
        rgb[mask == cls] = c
    return rgb

def show_prediction(idx):
    img, mask = full_dataset[idx]
    img_t = img.unsqueeze(0).to(device)

    with torch.no_grad():
        logits = model(img_t)
        pred = logits.argmax(1).squeeze().cpu().numpy()

    # ---- FIX: Unnormalize ----
    mean = np.array([0.485, 0.456, 0.406])
    std  = np.array([0.229, 0.224, 0.225])
    img_disp = img.permute(1,2,0).cpu().numpy()
    img_disp = (img_disp * std + mean).clip(0,1)  # FIXED

    gt_disp  = colorize(mask.numpy())
    pr_disp  = colorize(pred)

    plt.figure(figsize=(12,4))
    plt.subplot(1,3,1); plt.title("Image"); plt.imshow(img_disp); plt.axis("off")
    plt.subplot(1,3,2); plt.title("Ground Truth"); plt.imshow(gt_disp); plt.axis("off")
    plt.subplot(1,3,3); plt.title("Prediction"); plt.imshow(pr_disp); plt.axis("off")
    plt.show()

show_prediction(0)
show_prediction(10)
show_prediction(30)
show_prediction(50)

# Cell A — Compute Pixel Accuracy & Per-class IoU for val_loader
import torch
import numpy as np
import json
from collections import defaultdict

device = "cuda"
num_classes = 5   # update if you change classes
model.load_state_dict(torch.load("best_model.pth", map_location=device))
model.eval()

def compute_metrics(loader, model, num_classes=5, device="cuda"):
    model.eval()
    pixel_correct = 0
    pixel_total = 0
    # accumulate IoU components per class
    intersections = np.zeros(num_classes, dtype=np.float64)
    unions = np.zeros(num_classes, dtype=np.float64)
    with torch.no_grad():
        for imgs, masks in loader:
            imgs = imgs.to(device)
            masks = masks.to(device)

            logits = model(imgs)
            preds = logits.argmax(dim=1)

            pixel_correct += (preds == masks).sum().item()
            pixel_total += masks.numel()

            for cls in range(num_classes):
                pred_c = (preds == cls)
                mask_c = (masks == cls)
                inter = (pred_c & mask_c).sum().item()
                union = (pred_c | mask_c).sum().item()
                intersections[cls] += inter
                unions[cls] += union

    pixel_acc = pixel_correct / pixel_total
    # per-class IoU (avoid divide by zero)
    ious = []
    for cls in range(num_classes):
        if unions[cls] > 0:
            ious.append(intersections[cls] / unions[cls])
        else:
            ious.append(float("nan"))  # class not present in dataset
    mean_iou = np.nanmean(ious)
    return pixel_acc, ious, mean_iou

pixel_acc, per_class_iou, mean_iou = compute_metrics(val_loader, model, num_classes=num_classes, device=device)
metrics = {
    "pixel_accuracy": float(pixel_acc),
    "per_class_iou": [None if np.isnan(x) else float(x) for x in per_class_iou],
    "mean_iou": float(mean_iou)
}
print("Pixel Accuracy:", metrics["pixel_accuracy"])
print("Per-class IoU:", metrics["per_class_iou"])
print("Mean IoU:", metrics["mean_iou"])

# Save metrics to disk
with open("seg_project/metrics.json", "w") as f:
    json.dump(metrics, f, indent=2)
print("Saved metrics to seg_project/metrics.json")

# === FIXED Cell B — detect objects only where overlay & pred exist ===
import os, cv2, numpy as np
from PIL import Image
from collections import Counter

os.makedirs("seg_project/boxed", exist_ok=True)

# Colors for bounding boxes
box_colors = {
    1: (0,255,0),   # building (green)
    2: (255,0,0),   # car (red)
    3: (0,0,255),   # tree (blue)
    4: (0,255,255), # sky (yellow)
}

def draw_and_count(idx):
    pred_path = f"seg_project/predictions/{idx:04d}_pred.png"
    overlay_path = f"seg_project/overlays/{idx:04d}_overlay.png"

    if not (os.path.exists(pred_path) and os.path.exists(overlay_path)):
        return None

    pred = np.array(Image.open(pred_path))
    img = np.array(Image.open(overlay_path))

    boxes_info = []
    counts = Counter()

    # iterate over classes 1–4 (ignore road=0)
    for cls in [1,2,3,4]:
        mask = (pred == cls).astype("uint8") * 255

        # connected components
        n, labels, stats, _ = cv2.connectedComponentsWithStats(mask)

        for i in range(1, n):
            x, y, w, h, area = stats[i]

            # tiny noise filter
            if area < 20:
                continue

            counts[cls] += 1
            boxes_info.append((cls, x, y, x+w, y+h, int(area)))

            color = box_colors.get(cls, (255,255,255))
            img_bgr = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
            cv2.rectangle(img_bgr, (x,y), (x+w,y+h), color, 2)
            cv2.putText(img_bgr, f"{cls}:{area}", (x, y-5),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.45, color, 1)
            img = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)

    # save boxed image
    out_path = f"seg_project/boxed/{idx:04d}_boxed.png"
    Image.fromarray(img).save(out_path)

    return {"idx": idx, "counts": dict(counts), "boxes": boxes_info}


# ==== RUN FOR ALL MATCHING FILES ====
pred_files = sorted(os.listdir("seg_project/predictions"))
overlay_files = sorted(os.listdir("seg_project/overlays"))

# take only indices that exist in both
indices = sorted(list(set(
    int(f[:4]) for f in pred_files
).intersection(
    set(int(f[:4]) for f in overlay_files)
)))

records = []
for idx in indices:
    r = draw_and_count(idx)
    if r:
        records.append(r)

print(f"Saved {len(records)} boxed images in seg_project/boxed/")

# Cell C — show grid of boxed overlays with counts
import matplotlib.pyplot as plt
from PIL import Image
import os

def show_grid_boxed(start=0, n=6, cols=3):
    files = sorted(os.listdir("seg_project/boxed"))
    sel = files[start:start+n]
    if len(sel) == 0:
        print("No boxed images found. Run Cell B first.")
        return
    rows = (len(sel) + cols - 1) // cols
    plt.figure(figsize=(4*cols, 3*rows))
    for i, fname in enumerate(sel):
        im = Image.open(os.path.join("seg_project/boxed", fname))
        plt.subplot(rows, cols, i+1)
        plt.imshow(im); plt.axis("off")
        # show counts (read from CSV or filenames)
        idx = int(fname.split("_")[0])
        # find counts from CSV (quick read)
        try:
            import csv
            with open("seg_project/object_counts.csv") as f:
                reader = csv.DictReader(f)
                for row in reader:
                    if int(row["idx"]) == idx:
                        counts_text = ", ".join([f"{k}:{row[f'class_{k}_count']}" for k in [1,2,3,4]])
                        break
                else:
                    counts_text = ""
        except Exception:
            counts_text = ""
        plt.title(f"{fname}\n{counts_text}", fontsize=9)
    plt.tight_layout()
    plt.show()

# Example: show first 6 boxed images
show_grid_boxed(start=0, n=6, cols=3)

# Cell D — print top 10 images with most objects (useful for demo)
import csv, heapq

rows = []
with open("seg_project/object_counts.csv") as f:
    reader = csv.DictReader(f)
    for r in reader:
        total = sum(int(r[f'class_{c}_count']) for c in [1,2,3,4])
        rows.append((total, int(r["idx"]), r))

top = heapq.nlargest(10, rows)
print("Top images by detected object count:")
for total, idx, r in top:
    print(f"idx={idx} total_objects={total} counts={{1:{r['class_1_count']}, 2:{r['class_2_count']}, 3:{r['class_3_count']}, 4:{r['class_4_count']}}}")

# Save a small JSON summary
import json
summary = {"pixel_accuracy_and_iou": None}
try:
    with open("seg_project/metrics.json") as f:
        summary["pixel_accuracy_and_iou"] = json.load(f)
except:
    pass
summary["top_images_by_objects"] = [{"idx": idx, "total": total, "counts": r} for total, idx, r in top]
with open("seg_project/summary.json","w") as f:
    json.dump(summary, f, indent=2)
print("Saved seg_project/summary.json")

import numpy as np
from PIL import Image
import os

pred_files = sorted(os.listdir("seg_project/predictions"))

vals = set()

for f in pred_files[:20]:  # check first 20 images
    arr = np.array(Image.open("seg_project/predictions/" + f))
    vals.update(np.unique(arr))

print("Unique predicted values in first 20 images:", vals)

import os

pred_dir = "seg_project/predictions"
files = sorted(os.listdir(pred_dir))

print("Total prediction files:", len(files))
for f in files[:10]:
    path = os.path.join(pred_dir, f)
    print(f, "size:", os.path.getsize(path))

import os

os.makedirs("seg_project/predictions", exist_ok=True)
os.makedirs("seg_project/overlays", exist_ok=True)

print("Prediction folders ready!")

import os
print(os.listdir("seg_project/checkpoints"))

import os

os.makedirs("synthetic_dataset/images", exist_ok=True)
os.makedirs("synthetic_dataset/masks", exist_ok=True)
os.makedirs("seg_project/checkpoints", exist_ok=True)
os.makedirs("seg_project/predictions", exist_ok=True)
os.makedirs("seg_project/overlays", exist_ok=True)
os.makedirs("seg_project/boxed", exist_ok=True)

print("All folders recreated!")

import cv2, numpy as np, os
from PIL import Image

os.makedirs("synthetic_dataset/images", exist_ok=True)
os.makedirs("synthetic_dataset/masks", exist_ok=True)

W, H = 512, 256
N = 120

for i in range(N):
    img = np.zeros((H, W, 3), dtype=np.uint8) + 50
    mask = np.zeros((H, W), dtype=np.uint8)

    # road
    img[160:, :] = (50, 50, 50)
    mask[160:, :] = 1

    # buildings
    for _ in range(5):
        x1 = np.random.randint(0, W-100)
        x2 = x1 + np.random.randint(30, 120)
        y2 = np.random.randint(80, 160)
        img[y2:H, x1:x2] = (150, 150, 150)
        mask[y2:H, x1:x2] = 2

    # trees
    for _ in range(4):
        x = np.random.randint(0, W-60)
        y = np.random.randint(80, 160)
        cv2.circle(img, (x, y), 20, (0, 150, 0), -1)
        cv2.circle(mask, (x, y), 20, 3, -1)

    # cars
    for _ in range(3):
        x = np.random.randint(0, W-80)
        y = np.random.randint(180, H-30)
        cv2.rectangle(img, (x, y), (x+40, y+20), (0, 0, 255), -1)
        cv2.rectangle(mask, (x, y), (x+40, y+20), 4, -1)

    Image.fromarray(img).save(f"synthetic_dataset/images/{i:04d}.png")
    Image.fromarray(mask).save(f"synthetic_dataset/masks/{i:04d}.png")

print("Synthetic dataset recreated!")

from torch.utils.data import Dataset, DataLoader, random_split
from torchvision import transforms
from PIL import Image
import numpy as np
import torch

class CityDataset(Dataset):
    def __init__(self, img_dir, mask_dir):
        import glob
        self.imgs = sorted(glob.glob(img_dir + "/*.png"))
        self.masks = sorted(glob.glob(mask_dir + "/*.png"))

        self.norm = transforms.Normalize(
            mean=[0.485,0.456,0.406],
            std=[0.229,0.224,0.225]
        )

    def __len__(self): return len(self.imgs)

    def __getitem__(self, idx):
        img = Image.open(self.imgs[idx]).convert("RGB")
        mask = Image.open(self.masks[idx])

        img = transforms.ToTensor()(img)
        img = self.norm(img)

        mask = torch.from_numpy(np.array(mask)).long()
        return img, mask

full_data = CityDataset("synthetic_dataset/images", "synthetic_dataset/masks")

val = int(0.15 * len(full_data))
train = len(full_data)-val

train_ds, val_ds = random_split(full_data, [train, val])

train_loader = DataLoader(train_ds, batch_size=4, shuffle=True)
val_loader = DataLoader(val_ds, batch_size=1)

print("Dataset loaded again:", len(full_data))

# ===== Cell 5: TinyBSCNet (Clean Working Version) =====

import torch
import torch.nn as nn
import torch.nn.functional as F

# --------------------------------------------------
# Conv Block
# --------------------------------------------------
class ConvBlock(nn.Module):
    def __init__(self, in_ch, out_ch):
        super().__init__()
        self.block = nn.Sequential(
            nn.Conv2d(in_ch, out_ch, 3, padding=1),
            nn.BatchNorm2d(out_ch),
            nn.ReLU(inplace=True),

            nn.Conv2d(out_ch, out_ch, 3, padding=1),
            nn.BatchNorm2d(out_ch),
            nn.ReLU(inplace=True),
        )
    def forward(self, x):
        return self.block(x)


# --------------------------------------------------
# Simple BFM (Boundary Feature Module)
# --------------------------------------------------
class SimpleBFM(nn.Module):
    def __init__(self, in_ch, out_ch):
        super().__init__()
        self.conv = nn.Conv2d(in_ch, out_ch, 3, padding=1)
        self.bn   = nn.BatchNorm2d(out_ch)
        self.relu = nn.ReLU(inplace=True)

    def forward(self, x):
        return self.relu(self.bn(self.conv(x)))


# --------------------------------------------------
# Simple ELPPM (Context Pyramid)
# --------------------------------------------------
class SimpleELPPM(nn.Module):
    def __init__(self, in_ch, out_ch):
        super().__init__()

        # Pyramid pooling
        self.p1 = nn.AdaptiveAvgPool2d(1)
        self.p2 = nn.AdaptiveAvgPool2d(2)
        self.p3 = nn.AdaptiveAvgPool2d(4)

        # Reduce channels
        self.c1 = nn.Conv2d(in_ch, out_ch, 1)
        self.c2 = nn.Conv2d(in_ch, out_ch, 1)
        self.c3 = nn.Conv2d(in_ch, out_ch, 1)

        # Fuse features
        self.fuse = nn.Conv2d(out_ch * 3, out_ch, 1)

    def forward(self, x):
        h, w = x.shape[2:]

        f1 = F.interpolate(self.c1(self.p1(x)), (h, w))
        f2 = F.interpolate(self.c2(self.p2(x)), (h, w))
        f3 = F.interpolate(self.c3(self.p3(x)), (h, w))

        return self.fuse(torch.cat([f1, f2, f3], dim=1))


# --------------------------------------------------
# TinyBSCNet (encoder → ELPPM → decoder → BFM)
# --------------------------------------------------
class TinyBSCNet(nn.Module):
    def __init__(self, num_classes=5):
        super().__init__()

        # ENCODER
        self.enc1 = ConvBlock(3,32)
        self.enc2 = ConvBlock(32,64)
        self.enc3 = ConvBlock(64,128)

        self.pool = nn.MaxPool2d(2,2)

        # BOTTLENECK
        self.bottleneck = ConvBlock(128,256)

        # CONTEXT
        self.elppm = SimpleELPPM(256,128)

        # DECODER
        self.up3 = nn.ConvTranspose2d(128,128,2,2)
        self.dec3 = ConvBlock(128+128,128)

        self.up2 = nn.ConvTranspose2d(128,64,2,2)
        self.dec2 = ConvBlock(64+64,64)

        self.up1 = nn.ConvTranspose2d(64,32,2,2)
        self.dec1 = ConvBlock(32+32,32)

        # BOUNDARY REFINEMENT
        self.bfm = SimpleBFM(32,32)

        # OUTPUT LAYER
        self.final = nn.Conv2d(32, num_classes, 1)

    def forward(self, x):
        # Encoder
        e1 = self.enc1(x); p1 = self.pool(e1)
        e2 = self.enc2(p1); p2 = self.pool(e2)
        e3 = self.enc3(p2); p3 = self.pool(e3)

        # Bottleneck + ELPPM
        b = self.bottleneck(p3)
        b = self.elppm(b)

        # Decoder
        u3 = self.up3(b)
        d3 = self.dec3(torch.cat([u3, e3], dim=1))

        u2 = self.up2(d3)
        d2 = self.dec2(torch.cat([u2, e2], dim=1))

        u1 = self.up1(d2)
        d1 = self.dec1(torch.cat([u1, e1], dim=1))

        # Boundary refinement
        d1 = self.bfm(d1)

        return self.final(d1)


# Create model
device = "cuda" if torch.cuda.is_available() else "cpu"
model = TinyBSCNet(num_classes=5).to(device)
print("Model ready on:", device)

# ===== FIXED Cell 6 — Training =====
import time, json, os
import torch
import torch.nn as nn
import torch.optim as optim
from torch.cuda.amp import autocast, GradScaler

torch.cuda.empty_cache()

EPOCHS = 20
LR = 3e-4
WEIGHT_DECAY = 1e-5

CHECKPOINT_DIR = "seg_project/checkpoints"
os.makedirs(CHECKPOINT_DIR, exist_ok=True)
BEST_PATH = os.path.join(CHECKPOINT_DIR, "best_model.pth")
HISTORY_PATH = os.path.join(CHECKPOINT_DIR, "history.json")

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Training on device:", device)

optimizer = optim.AdamW(model.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)
criterion = nn.CrossEntropyLoss()

# OLD STYLE WORKS ON ALL PYTORCH VERSIONS
scaler = GradScaler()

best_val = float("inf")
history = {"train_loss": [], "val_loss": []}

for epoch in range(1, EPOCHS + 1):
    t0 = time.time()
    model.train()
    train_loss_sum = 0
    n = 0

    for imgs, masks in train_loader:
        imgs = imgs.to(device)
        masks = masks.to(device)

        optimizer.zero_grad()

        # Mixed precision
        with autocast():
            logits = model(imgs)
            loss = criterion(logits, masks)

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        train_loss_sum += loss.item() * imgs.size(0)
        n += imgs.size(0)

    train_loss = train_loss_sum / n

    # Validation
    model.eval()
    val_loss_sum = 0
    vn = 0

    with torch.no_grad():
        for imgs, masks in val_loader:
            imgs = imgs.to(device)
            masks = masks.to(device)

            with autocast():
                logits = model(imgs)
                loss = criterion(logits, masks)

            val_loss_sum += loss.item() * imgs.size(0)
            vn += imgs.size(0)

    val_loss = val_loss_sum / vn

    history["train_loss"].append(train_loss)
    history["val_loss"].append(val_loss)

    print(f"Epoch {epoch}/{EPOCHS} | Train={train_loss:.4f} | Val={val_loss:.4f} | Time={(time.time() - t0):.1f}s")

    if val_loss < best_val:
        best_val = val_loss
        torch.save(model.state_dict(), BEST_PATH)
        print(" → Saved best_model.pth")

    with open(HISTORY_PATH, "w") as f:
        json.dump(history, f)

print("Training complete! Best validation loss:", best_val)
torch.cuda.empty_cache()
print("Checkpoint folder:", os.listdir(CHECKPOINT_DIR))

# ===== Cell 7 — Generate Predictions + Overlays =====
import os
import torch
import numpy as np
from PIL import Image

# Load best model
model.load_state_dict(torch.load("seg_project/checkpoints/best_model.pth", map_location=device))
model.eval()

os.makedirs("seg_project/predictions", exist_ok=True)
os.makedirs("seg_project/overlays", exist_ok=True)

# Unnormalize for display
def unnormalize(img):
    mean = torch.tensor([0.485,0.456,0.406]).view(3,1,1)
    std  = torch.tensor([0.229,0.224,0.225]).view(3,1,1)
    return (img * std + mean).clamp(0,1)

color_map = {
    0: (0,0,0),       # background
    1: (128,64,128),  # road
    2: (70,70,70),    # building
    3: (0,255,0),     # tree
    4: (255,0,0),     # car
}

print("Generating predictions and overlays...")

for i in range(len(full_data)):
    img_t, mask_t = full_data[i]
    img_in = img_t.unsqueeze(0).to(device)

    with torch.no_grad():
        pred = model(img_in).argmax(dim=1).squeeze().cpu().numpy()

    # Save prediction mask
    Image.fromarray(pred.astype(np.uint8)).save(f"seg_project/predictions/{i:04d}.png")

    # Create overlay
    base = (unnormalize(img_t).permute(1,2,0).numpy() * 255).astype(np.uint8)
    overlay = base.copy()

    for cls, color in color_map.items():
        overlay[pred == cls] = (
            0.6 * overlay[pred == cls] + 0.4 * np.array(color)
        ).astype(np.uint8)

    Image.fromarray(overlay).save(f"seg_project/overlays/{i:04d}.png")

print("Done! Check seg_project/overlays/")

import os
print("Predictions:", len(os.listdir("seg_project/predictions")))
print("Overlays:", len(os.listdir("seg_project/overlays")))

# ===== Cell 8 — Display Overlay Grid =====
import os
import matplotlib.pyplot as plt
from PIL import Image

def show_overlay_grid(n=9, start=0):
    files = sorted(os.listdir("seg_project/overlays"))
    selected = files[start:start+n]

    cols = 3
    rows = (n + cols - 1) // cols

    plt.figure(figsize=(12, 8))
    for i, fname in enumerate(selected):
        img = Image.open(os.path.join("seg_project/overlays", fname))
        plt.subplot(rows, cols, i+1)
        plt.imshow(img)
        plt.title(fname)
        plt.axis("off")

    plt.tight_layout()
    plt.show()

# Show first 9 overlays
show_overlay_grid(9, start=0)

# ===== Cell 9 — Bounding Boxes =====
import cv2
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

BOX_COLORS = {
    1: (255, 0, 0),     # road - red
    2: (0, 255, 0),     # building - green
    3: (0, 0, 255),     # tree - blue
    4: (255, 255, 0),   # car - yellow
}

def draw_boxes(idx):
    pred_path = f"seg_project/predictions/{idx:04d}.png"
    overlay_path = f"seg_project/overlays/{idx:04d}.png"

    pred = np.array(Image.open(pred_path))
    img = cv2.cvtColor(np.array(Image.open(overlay_path)), cv2.COLOR_RGB2BGR)

    for cls in [1, 2, 3, 4]:
        mask = (pred == cls).astype("uint8") * 255
        contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

        for cnt in contours:
            area = cv2.contourArea(cnt)
            if area < 40:  # ignore tiny dots
                continue
            x, y, w, h = cv2.boundingRect(cnt)
            cv2.rectangle(img, (x, y), (x+w, y+h), BOX_COLORS[cls], 2)
            cv2.putText(img, f"class {cls}", (x, y-5),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.5, BOX_COLORS[cls], 1)

    # Show
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    plt.figure(figsize=(8, 5))
    plt.imshow(img)
    plt.axis("off")
    plt.show()

# Example for image 0
draw_boxes(0)

# ===== Cell 10 — Object Counting =====
import csv

def count_objects(idx):
    pred_path = f"seg_project/predictions/{idx:04d}.png"
    pred = np.array(Image.open(pred_path))

    counts = {
        "road": (pred == 1).sum(),
        "building": (pred == 2).sum(),
        "tree": (pred == 3).sum(),
        "car": (pred == 4).sum(),
    }
    return counts

# Save counts for all images
with open("seg_project/object_counts.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerow(["image", "road_pixels", "building_pixels", "tree_pixels", "car_pixels"])

    for i in range(len(full_data)):
        c = count_objects(i)
        writer.writerow([i, c["road"], c["building"], c["tree"], c["car"]])

print("Saved counts → seg_project/object_counts.csv")
print("Example counts for image 0:", count_objects(0))

# ===== Cell 11 — Compute Accuracy + Mean IoU =====
import torch
import numpy as np

def compute_metrics():
    model.eval()
    pixel_correct = 0
    pixel_total = 0
    iou_list = []

    with torch.no_grad():
        for imgs, masks in val_loader:
            imgs, masks = imgs.cuda(), masks.cuda()

            pred = model(imgs).argmax(1)

            pixel_correct += (pred == masks).sum().item()
            pixel_total += masks.numel()

            for cls in range(5):
                pred_c = (pred == cls)
                mask_c = (masks == cls)
                inter = (pred_c & mask_c).sum().item()
                union = (pred_c | mask_c).sum().item()
                if union > 0:
                    iou_list.append(inter / union)

    acc = pixel_correct / pixel_total
    miou = np.mean(iou_list)

    return acc, miou

acc, miou = compute_metrics()
print("Pixel Accuracy:", acc)
print("Mean IoU:", miou)

# ===== FINAL SHOWCASE CELL =====

import matplotlib.pyplot as plt
from PIL import Image
import numpy as np
import cv2
from collections import Counter

def show_full_result(idx, min_area=5):
    print(f"\n=== RESULT FOR IMAGE {idx} ===\n")

    # -------- 1. Load original image --------
    orig_path = f"seg_project/images/{idx:04d}.png"
    orig = np.array(Image.open(orig_path))

    # -------- 2. Load segmentation overlay --------
    overlay_path = f"seg_project/overlays/{idx:04d}.png"
    overlay = np.array(Image.open(overlay_path))

    # -------- 3. Load predicted mask --------
    pred_path = f"seg_project/predictions/{idx:04d}.png"
    pred = np.array(Image.open(pred_path))

    # -------- 4. Create bounding-box image --------
    boxed = overlay.copy()
    pred_mask = pred.copy()

    colors = {
        1: (255, 0, 0),   # road
        2: (0, 255, 0),   # building
        3: (0, 0, 255),   # trees
        4: (255, 255, 0)  # cars
    }

    counts = Counter()

    for cls in [1,2,3,4]:
        cls_mask = (pred_mask == cls).astype('uint8') * 255
        contours, _ = cv2.findContours(cls_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

        for cnt in contours:
            area = cv2.contourArea(cnt)
            if area < min_area:
                continue

            x,y,w,h = cv2.boundingRect(cnt)
            cv2.rectangle(boxed, (x,y), (x+w,y+h), colors[cls], 2)
            cv2.putText(boxed, f"C{cls}", (x, y-5), cv2.FONT_HERSHEY_SIMPLEX, 0.5, colors[cls], 1)

            counts[cls] += 1

    # -------- 5. Show results in grid --------
    plt.figure(figsize=(16,5))

    plt.subplot(1,3,1)
    plt.title("Original Image")
    plt.imshow(orig)
    plt.axis("off")

    plt.subplot(1,3,2)
    plt.title("Segmentation Output")
    plt.imshow(overlay)
    plt.axis("off")

    plt.subplot(1,3,3)
    plt.title("Detection + BBoxes")
    plt.imshow(boxed)
    plt.axis("off")

    plt.show()

    # -------- 6. Print object counts --------
    print("\nObject Counts:")
    print("--------------")
    names = {1:"Road", 2:"Building", 3:"Tree", 4:"Car"}
    for cls in [1,2,3,4]:
        print(f"{names[cls]}: {counts[cls]}")

    print("\n===================================\n")

import os

print("Folders in project root:", os.listdir("."))

if os.path.exists("city_dataset/images"):
    print("\ncity_dataset/images:", len(os.listdir("city_dataset/images")), "files")

if os.path.exists("synthetic_dataset/images"):
    print("\nsynthetic_dataset/images:", len(os.listdir("synthetic_dataset/images")), "files")

import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
import cv2
import torch

# Set correct original image folder
IMG_DIR = "synthetic_dataset/images"
PRED_DIR = "seg_project/predictions"
OVR_DIR = "seg_project/overlays"

# class-to-color map
color_map = {
    0: (0,0,0),
    1: (255,0,0),   # building
    2: (0,255,0),   # road
    3: (0,0,255),   # trees
    4: (255,255,0), # vehicles
}

# colors for bounding boxes
box_colors = {
    1: (0,0,255),   # red
    2: (0,255,0),   # green
    3: (255,0,0),   # blue
    4: (0,255,255), # yellow
}

def show_full_result(idx, min_area=30):
    print(f"\n========== RESULT FOR IMAGE {idx} ==========\n")

    # -------- 1. LOAD ALL FILES --------
    orig = np.array(Image.open(f"{IMG_DIR}/{idx:04d}.png"))
    pred = np.array(Image.open(f"{PRED_DIR}/{idx:04d}_pred.png"))
    overlay = np.array(Image.open(f"{OVR_DIR}/{idx:04d}_overlay.png"))

    # -------- 2. Find bounding boxes --------
    boxes = []
    for cls in [1,2,3,4]:
        mask = (pred == cls).astype('uint8') * 255
        cnts, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

        for c in cnts:
            area = cv2.contourArea(c)
            if area < min_area: continue
            x,y,w,h = cv2.boundingRect(c)
            boxes.append((cls, x,y,w,h, area))

    # -------- 3. Draw bounding boxes --------
    boxed = overlay.copy()
    boxed_cv = cv2.cvtColor(boxed, cv2.COLOR_RGB2BGR)

    for cls, x,y,w,h, area in boxes:
        cv2.rectangle(boxed_cv, (x,y), (x+w, y+h), box_colors[cls], 2)
        cv2.putText(boxed_cv, f"C{cls}", (x, y-5),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.5, box_colors[cls], 1)

    boxed = cv2.cvtColor(boxed_cv, cv2.COLOR_BGR2RGB)

    # -------- 4. Display everything in grid --------
    fig, ax = plt.subplots(1, 4, figsize=(18,4))

    ax[0].set_title("Original Image")
    ax[0].imshow(orig)
    ax[0].axis('off')

    ax[1].set_title("Prediction Mask")
    ax[1].imshow(pred, cmap="tab20")
    ax[1].axis('off')

    ax[2].set_title("Overlay")
    ax[2].imshow(overlay)
    ax[2].axis('off')

    ax[3].set_title(f"Detected Objects: {len(boxes)}")
    ax[3].imshow(boxed)
    ax[3].axis('off')

    plt.show()

    print("Detected boxes:")
    for b in boxes:
        print(b)

    return boxes

import os

print("Prediction files:", sorted(os.listdir("seg_project/predictions"))[:20])

import cv2
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

# Path shortcuts
IMG_DIR = "synthetic_dataset/images"
PRED_DIR = "seg_project/predictions"
OVR_DIR = "seg_project/overlays"

def show_full_result(idx, min_area=20):
    idx_str = f"{idx:04d}"

    # ---------- Load files ----------
    orig = np.array(Image.open(f"{IMG_DIR}/{idx_str}.png"))
    pred = np.array(Image.open(f"{PRED_DIR}/{idx_str}.png"))     # FIXED
    overlay = np.array(Image.open(f"{OVR_DIR}/{idx_str}_overlay.png"))

    # ---------- Object counting ----------
    counts = {}
    for cls in [1,2,3,4]:
        mask = (pred == cls).astype(np.uint8) * 255
        contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        cnt = sum(1 for c in contours if cv2.contourArea(c) >= min_area)
        counts[cls] = cnt

    # ---------- Draw bounding boxes ----------
    img_boxed = cv2.cvtColor(orig.copy(), cv2.COLOR_RGB2BGR)

    colors = {
        1: (0,0,255),
        2: (0,255,0),
        3: (255,0,0),
        4: (0,255,255),
    }

    for cls in colors:
        mask = (pred == cls).astype(np.uint8) * 255
        contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

        for c in contours:
            area = cv2.contourArea(c)
            if area < min_area:
                continue

            x, y, w, h = cv2.boundingRect(c)
            cv2.rectangle(img_boxed, (x,y), (x+w,y+h), colors[cls], 2)
            cv2.putText(img_boxed, f"C{cls}", (x,y-5),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.6, colors[cls], 2)

    img_boxed = cv2.cvtColor(img_boxed, cv2.COLOR_BGR2RGB)

    # ---------- Show results ----------
    print(f"\n========== RESULT FOR IMAGE {idx} ==========\n")
    print("Object counts:", counts)

    fig, ax = plt.subplots(1, 3, figsize=(15,5))

    ax[0].set_title("Original Image")
    ax[0].imshow(orig)
    ax[0].axis("off")

    ax[1].set_title("Segmentation Overlay")
    ax[1].imshow(overlay)
    ax[1].axis("off")

    ax[2].set_title("Detected Objects (Boxes)")
    ax[2].imshow(img_boxed)
    ax[2].axis("off")

    plt.show()

import os
print("OVERLAY FILES:", sorted(os.listdir("seg_project/overlays"))[:20])

import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
import os
import cv2

IMG_DIR  = "synthetic_dataset/images"
PRED_DIR = "seg_project/predictions"
OVR_DIR  = "seg_project/overlays"

def show_full_result(idx, min_area=20):

    idx_str = f"{idx:04d}.png"

    # ----- 1. Load images -----
    orig    = np.array(Image.open(f"{IMG_DIR}/{idx_str}"))
    pred    = np.array(Image.open(f"{PRED_DIR}/{idx_str}"))
    overlay = np.array(Image.open(f"{OVR_DIR}/{idx_str}"))

    # ----- 2. Object counting -----
    counts = {}
    for cls in [1,2,3,4]:
        mask = (pred == cls).astype("uint8") * 255
        contours,_ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        counts[cls] = sum(1 for c in contours if cv2.contourArea(c) >= min_area)

    # ----- 3. Drawing bounding boxes -----
    boxed = overlay.copy()
    colors = {
        1:(255,0,0),
        2:(0,255,0),
        3:(0,0,255),
        4:(255,255,0),
    }
    for cls in [1,2,3,4]:
        mask = (pred == cls).astype("uint8") * 255
        contours,_ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        for c in contours:
            if cv2.contourArea(c) < min_area:
                continue
            x,y,w,h = cv2.boundingRect(c)
            cv2.rectangle(boxed, (x,y), (x+w,y+h), colors[cls], 2)
            cv2.putText(boxed, f"C{cls}", (x,y-4),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.5, colors[cls], 1)

    # ----- 4. Show everything -----
    fig, ax = plt.subplots(1, 4, figsize=(22,6))
    ax[0].imshow(orig);    ax[0].set_title("Original Image"); ax[0].axis("off")
    ax[1].imshow(pred);    ax[1].set_title("Prediction Mask"); ax[1].axis("off")
    ax[2].imshow(overlay); ax[2].set_title("Segmentation Overlay"); ax[2].axis("off")
    ax[3].imshow(boxed);   ax[3].set_title("Detected Objects"); ax[3].axis("off")

    plt.show()

    print("\n=== OBJECT COUNTS ===")
    print(counts)

show_full_result(0)

show_full_result(5)

show_full_result(10)

show_full_result(25)

show_full_result(119)

import os
print(os.listdir("."))

print(os.listdir(".."))

import os

os.makedirs("extra_test", exist_ok=True)
print("extra_test folder ready!")

from google.colab import files
uploaded = files.upload()

import shutil, os

os.makedirs("extra_test", exist_ok=True)

src = "car.png"         # because you uploaded it manually
dst = "extra_test/0000.png"

shutil.copy(src, dst)

print("Copied to:", dst)

# ===== TinyBSCNet definition =====
import torch
import torch.nn as nn
import torch.nn.functional as F

class ConvBlock(nn.Module):
    def __init__(self, in_ch, out_ch):
        super().__init__()
        self.block = nn.Sequential(
            nn.Conv2d(in_ch, out_ch, 3, padding=1),
            nn.BatchNorm2d(out_ch),
            nn.ReLU(inplace=True),

            nn.Conv2d(out_ch, out_ch, 3, padding=1),
            nn.BatchNorm2d(out_ch),
            nn.ReLU(inplace=True),
        )
    def forward(self, x):
        return self.block(x)

class SimpleBFM(nn.Module):
    def __init__(self, in_ch, out_ch):
        super().__init__()
        self.conv = nn.Conv2d(in_ch, out_ch, 3, padding=1)
        self.bn   = nn.BatchNorm2d(out_ch)
        self.relu = nn.ReLU(inplace=True)
    def forward(self, x):
        return self.relu(self.bn(self.conv(x)))

class SimpleELPPM(nn.Module):
    def __init__(self, in_ch, out_ch):
        super().__init__()
        self.p1 = nn.AdaptiveAvgPool2d(1)
        self.p2 = nn.AdaptiveAvgPool2d(2)
        self.p3 = nn.AdaptiveAvgPool2d(4)
        self.c1 = nn.Conv2d(in_ch, out_ch, 1)
        self.c2 = nn.Conv2d(in_ch, out_ch, 1)
        self.c3 = nn.Conv2d(in_ch, out_ch, 1)
        self.fuse = nn.Conv2d(out_ch * 3, out_ch, 1)

    def forward(self, x):
        h, w = x.shape[2:]
        f1 = F.interpolate(self.c1(self.p1(x)), (h, w))
        f2 = F.interpolate(self.c2(self.p2(x)), (h, w))
        f3 = F.interpolate(self.c3(self.p3(x)), (h, w))
        return self.fuse(torch.cat([f1, f2, f3], dim=1))

class TinyBSCNet(nn.Module):
    def __init__(self, num_classes=5):
        super().__init__()
        self.enc1 = ConvBlock(3,32)
        self.enc2 = ConvBlock(32,64)
        self.enc3 = ConvBlock(64,128)

        self.pool = nn.MaxPool2d(2,2)

        self.bottleneck = ConvBlock(128,256)
        self.elppm = SimpleELPPM(256,128)

        self.up3 = nn.ConvTranspose2d(128,128,2,2)
        self.dec3 = ConvBlock(128+128,128)

        self.up2 = nn.ConvTranspose2d(128,64,2,2)
        self.dec2 = ConvBlock(64+64,64)

        self.up1 = nn.ConvTranspose2d(64,32,2,2)
        self.dec1 = ConvBlock(32+32,32)

        self.bfm = SimpleBFM(32,32)
        self.final = nn.Conv2d(32, 5, 1)

    def forward(self, x):
        e1 = self.enc1(x); p1 = self.pool(e1)
        e2 = self.enc2(p1); p2 = self.pool(e2)
        e3 = self.enc3(p2); p3 = self.pool(e3)

        b = self.bottleneck(p3)
        b = self.elppm(b)

        u3 = self.up3(b)
        d3 = self.dec3(torch.cat([u3, e3], dim=1))

        u2 = self.up2(d3)
        d2 = self.dec2(torch.cat([u2, e2], dim=1))

        u1 = self.up1(d2)
        d1 = self.dec1(torch.cat([u1, e1], dim=1))

        d1 = self.bfm(d1)
        return self.final(d1)

import os
for root, dirs, files in os.walk(".", topdown=True):
    print(root, files)

import os

os.makedirs("seg_project/checkpoints", exist_ok=True)
os.makedirs("seg_project/predictions", exist_ok=True)
os.makedirs("seg_project/overlays", exist_ok=True)
os.makedirs("seg_project/boxed", exist_ok=True)

os.makedirs("synthetic_dataset/images", exist_ok=True)
os.makedirs("synthetic_dataset/masks", exist_ok=True)

print("Folders are ready!")

import os, cv2, numpy as np
from PIL import Image

IMG_W, IMG_H = 512, 256
NUM_IMAGES = 120

for i in range(NUM_IMAGES):
    img = np.zeros((IMG_H, IMG_W, 3), dtype=np.uint8)
    mask = np.zeros((IMG_H, IMG_W), dtype=np.uint8)

    # road
    cv2.rectangle(img, (0, 150), (IMG_W, IMG_H), (50, 50, 50), -1)
    mask[150:IMG_H, :] = 1

    # sky
    img[:80, :] = (135, 206, 235)
    mask[:80, :] = 0

    # buildings
    for _ in range(np.random.randint(1, 5)):
        x1 = np.random.randint(0, IMG_W - 80)
        x2 = x1 + np.random.randint(40, 80)
        y2 = 150
        y1 = np.random.randint(80, 150)
        cv2.rectangle(img, (x1, y1), (x2, y2), (200, 200, 200), -1)
        mask[y1:y2, x1:x2] = 2

    # cars
    for _ in range(np.random.randint(1, 4)):
        w = np.random.randint(40, 70)
        h = np.random.randint(20, 35)
        x1 = np.random.randint(0, IMG_W - w)
        y1 = np.random.randint(160, IMG_H - 30)
        cv2.rectangle(img, (x1, y1), (x1 + w, y1 + h), (0, 0, 255), -1)
        mask[y1:y1+h, x1:x1+w] = 3

    # trees
    for _ in range(np.random.randint(1, 4)):
        x = np.random.randint(0, IMG_W - 30)
        y = np.random.randint(80, 150)
        cv2.circle(img, (x, y), 25, (0, 255, 0), -1)
        mask[y-25:y+25, x-25:x+25] = 4

    Image.fromarray(img).save(f"synthetic_dataset/images/{i:04d}.png")
    Image.fromarray(mask).save(f"synthetic_dataset/masks/{i:04d}.png")

print("Dataset created!")

# ===== Step 3A — Dataset Loader =====
import torch
from torch.utils.data import Dataset, DataLoader, random_split
from torchvision import transforms
from PIL import Image
import numpy as np
import glob

RESIZE = (512, 256)

class CityDataset(Dataset):
    def __init__(self, img_folder, mask_folder):
        self.img_paths = sorted(glob.glob(img_folder + "/*.png"))
        self.mask_paths = sorted(glob.glob(mask_folder + "/*.png"))

        self.normalize = transforms.Normalize(
            mean=[0.485, 0.456, 0.406],
            std=[0.229, 0.224, 0.225]
        )

    def __len__(self):
        return len(self.img_paths)

    def __getitem__(self, idx):
        img = Image.open(self.img_paths[idx]).convert("RGB")
        mask = Image.open(self.mask_paths[idx])

        img = img.resize(RESIZE, Image.BILINEAR)
        mask = mask.resize(RESIZE, Image.NEAREST)

        img = transforms.ToTensor()(img)
        img = self.normalize(img)

        mask = torch.from_numpy(np.array(mask)).long()

        return img, mask

print("CityDataset class ready!")

IMG_DIR = "synthetic_dataset/images"
MASK_DIR = "synthetic_dataset/masks"

full_dataset = CityDataset(IMG_DIR, MASK_DIR)

val_size = int(0.15 * len(full_dataset))
train_size = len(full_dataset) - val_size

train_ds, val_ds = random_split(full_dataset, [train_size, val_size])

train_loader = DataLoader(train_ds, batch_size=4, shuffle=True)
val_loader = DataLoader(val_ds, batch_size=1)

print("Training samples:", train_size)
print("Validation samples:", val_size)

# ===== Step 3C — TinyBSCNet =====
import torch.nn as nn
import torch.nn.functional as F

class ConvBlock(nn.Module):
    def __init__(self, in_ch, out_ch):
        super().__init__()
        self.block = nn.Sequential(
            nn.Conv2d(in_ch, out_ch, 3, padding=1),
            nn.BatchNorm2d(out_ch),
            nn.ReLU(inplace=True),
            nn.Conv2d(out_ch, out_ch, 3, padding=1),
            nn.BatchNorm2d(out_ch),
            nn.ReLU(inplace=True),
        )
    def forward(self, x):
        return self.block(x)

class SimpleBFM(nn.Module):
    def __init__(self, in_ch, out_ch):
        super().__init__()
        self.conv = nn.Conv2d(in_ch, out_ch, 3, padding=1)
        self.bn = nn.BatchNorm2d(out_ch)
        self.relu = nn.ReLU(inplace=True)

    def forward(self, x):
        return self.relu(self.bn(self.conv(x)))

class SimpleELPPM(nn.Module):
    def __init__(self, in_ch, out_ch):
        super().__init__()
        self.p1 = nn.AdaptiveAvgPool2d(1)
        self.p2 = nn.AdaptiveAvgPool2d(2)
        self.p3 = nn.AdaptiveAvgPool2d(4)

        self.c1 = nn.Conv2d(in_ch, out_ch, 1)
        self.c2 = nn.Conv2d(in_ch, out_ch, 1)
        self.c3 = nn.Conv2d(in_ch, out_ch, 1)

        self.fuse = nn.Conv2d(out_ch*3, out_ch, 1)

    def forward(self, x):
        h, w = x.shape[2:]
        f1 = F.interpolate(self.c1(self.p1(x)), (h, w))
        f2 = F.interpolate(self.c2(self.p2(x)), (h, w))
        f3 = F.interpolate(self.c3(self.p3(x)), (h, w))
        return self.fuse(torch.cat([f1, f2, f3], dim=1))

class TinyBSCNet(nn.Module):
    def __init__(self, num_classes=5):
        super().__init__()
        self.enc1 = ConvBlock(3,32)
        self.enc2 = ConvBlock(32,64)
        self.enc3 = ConvBlock(64,128)
        self.pool = nn.MaxPool2d(2,2)

        self.bottleneck = ConvBlock(128,256)
        self.elppm = SimpleELPPM(256,128)

        self.up3 = nn.ConvTranspose2d(128,128,2,2)
        self.dec3 = ConvBlock(256,128)

        self.up2 = nn.ConvTranspose2d(128,64,2,2)
        self.dec2 = ConvBlock(128,64)

        self.up1 = nn.ConvTranspose2d(64,32,2,2)
        self.dec1 = ConvBlock(64,32)

        self.bfm = SimpleBFM(32,32)
        self.final = nn.Conv2d(32,5,1)

    def forward(self, x):
        e1 = self.enc1(x); p1 = self.pool(e1)
        e2 = self.enc2(p1); p2 = self.pool(e2)
        e3 = self.enc3(p2); p3 = self.pool(e3)
        b = self.bottleneck(p3)
        b = self.elppm(b)
        u3 = self.up3(b); d3 = self.dec3(torch.cat([u3, e3], dim=1))
        u2 = self.up2(d3); d2 = self.dec2(torch.cat([u2, e2], dim=1))
        u1 = self.up1(d2); d1 = self.dec1(torch.cat([u1, e1], dim=1))
        d1 = self.bfm(d1)
        return self.final(d1)

device = "cuda"
model = TinyBSCNet(num_classes=5).to(device)
print("Model initialized!")

# ===== Step 4 — Train TinyBSCNet (Compatible With Your PyTorch Version) =====
import torch
import torch.nn as nn
import torch.optim as optim
from torch.cuda.amp import autocast, GradScaler
import time

device = "cuda"
EPOCHS = 20
LR = 3e-4
WEIGHT_DECAY = 1e-5

optimizer = optim.AdamW(model.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)
criterion = nn.CrossEntropyLoss()

# OLD STYLE SCALER (your version supports this)
scaler = GradScaler()

best_val = float("inf")
history = {"train_loss": [], "val_loss": []}

print("Training on:", device)

for epoch in range(1, EPOCHS + 1):
    model.train()
    t0 = time.time()
    running = 0.0

    # ---------- TRAIN ----------
    for imgs, masks in train_loader:
        imgs = imgs.to(device)
        masks = masks.to(device)

        optimizer.zero_grad()

        # OLD AUTOSTYLE (your PyTorch supports this)
        with autocast():
            logits = model(imgs)
            loss = criterion(logits, masks)

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        running += loss.item() * imgs.size(0)

    train_loss = running / len(train_loader.dataset)

    # ---------- VALIDATION ----------
    model.eval()
    v_running = 0.0
    with torch.no_grad():
        for imgs, masks in val_loader:
            imgs = imgs.to(device)
            masks = masks.to(device)

            with autocast():
                logits = model(imgs)
                loss = criterion(logits, masks)

            v_running += loss.item() * imgs.size(0)

    val_loss = v_running / len(val_loader.dataset)

    history["train_loss"].append(train_loss)
    history["val_loss"].append(val_loss)

    print(f"Epoch {epoch}/{EPOCHS} | Train={train_loss:.4f} | Val={val_loss:.4f} | Time={time.time()-t0:.1f}s")

    # Save best model
    if val_loss < best_val:
        best_val = val_loss
        torch.save(model.state_dict(), "seg_project/checkpoints/best_model.pth")
        print(" → Saved best_model.pth")

print("\nTraining complete!")
print("Best validation loss:", best_val)

# ===== Step 5 — Generate Predictions =====
import os
import torch
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

device = "cuda"

IMG_DIR = "synthetic_dataset/images"
PRED_DIR = "seg_project/predictions"
OVR_DIR = "seg_project/overlays"

os.makedirs(PRED_DIR, exist_ok=True)
os.makedirs(OVR_DIR, exist_ok=True)

# Load model
model = TinyBSCNet(num_classes=5).to(device)
model.load_state_dict(torch.load("seg_project/checkpoints/best_model.pth", map_location=device))
model.eval()

print("Model loaded, starting predictions...")

def overlay_mask(image, mask):
    """Add transparent color overlay."""
    image = image.copy()
    colors = [
        (0,0,0),        # class 0
        (255,0,0),      # class 1 - red
        (0,255,0),      # class 2 - green
        (0,0,255),      # class 3 - blue
        (255,255,0)     # class 4 - yellow
    ]

    overlay = Image.new("RGBA", image.size)
    pix = overlay.load()

    mask_np = np.array(mask)
    for y in range(mask_np.shape[0]):
        for x in range(mask_np.shape[1]):
            cls = mask_np[y, x]
            r,g,b = colors[cls]
            pix[x, y] = (r, g, b, 80)   # Transparent

    return Image.alpha_composite(image.convert("RGBA"), overlay)

# ----- Predict all images -----
files = sorted(os.listdir(IMG_DIR))
count = 0

for fname in files:
    if not fname.endswith(".png"):
        continue

    path = f"{IMG_DIR}/{fname}"
    img = Image.open(path).convert("RGB")
    arr = np.array(img).astype(np.float32) / 255.0

    # HWC → CHW
    tensor = torch.tensor(arr).permute(2,0,1).unsqueeze(0).to(device)

    with torch.no_grad():
        logits = model(tensor)
        pred = logits.argmax(1).squeeze().cpu().numpy().astype(np.uint8)

    # Save prediction
    Image.fromarray(pred).save(f"{PRED_DIR}/{fname}")

    # Save overlay
    over = overlay_mask(img, pred)
    over.save(f"{OVR_DIR}/{fname}")

    count += 1

print("Done! Predictions created:", count)
print("Prediction folder:", os.listdir(PRED_DIR)[:10])
print("Overlay folder:", os.listdir(OVR_DIR)[:10])

# ===== Step 6 — Visualization Grid =====
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image
import os

IMG_DIR = "synthetic_dataset/images"
PRED_DIR = "seg_project/predictions"
OVR_DIR  = "seg_project/overlays"

files = sorted(os.listdir(IMG_DIR))[:9]  # show first 9

plt.figure(figsize=(14, 14))

for i, fname in enumerate(files):
    orig = np.array(Image.open(f"{IMG_DIR}/{fname}"))
    pred = np.array(Image.open(f"{PRED_DIR}/{fname}"))
    over = np.array(Image.open(f"{OVR_DIR}/{fname}"))

    # Show original
    plt.subplot(9, 3, 3*i + 1)
    plt.imshow(orig)
    plt.title("Original")
    plt.axis("off")

    # Show mask
    plt.subplot(9, 3, 3*i + 2)
    plt.imshow(pred, cmap="nipy_spectral")
    plt.title("Mask")
    plt.axis("off")

    # Show overlay
    plt.subplot(9, 3, 3*i + 3)
    plt.imshow(over)
    plt.title("Overlay")
    plt.axis("off")

plt.tight_layout()
plt.show()

# ===== Step 7 — Run Segmentation on car.png =====
import torch
import numpy as np
from PIL import Image, ImageDraw
import matplotlib.pyplot as plt
import torch.nn.functional as F

# Paths
TEST_IMG = "/content/car.png"

# Load image
orig = Image.open(TEST_IMG).convert("RGB")
img_resized = orig.resize((256, 256))
arr = np.array(img_resized).astype(np.float32) / 255.0

# Convert to tensor (1,3,H,W)
tensor = torch.tensor(arr).permute(2,0,1).unsqueeze(0).to("cuda")

# Load model
model = TinyBSCNet(num_classes=5).to("cuda")
model.load_state_dict(torch.load("seg_project/checkpoints/best_model.pth", map_location="cuda"))
model.eval()

# Run inference
with torch.no_grad():
    logits = model(tensor)
    pred = logits.argmax(1).squeeze().cpu().numpy().astype(np.uint8)

# Resize prediction back to original size
pred_big = Image.fromarray(pred).resize(orig.size, resample=Image.NEAREST)
pred_np = np.array(pred_big)

# Color overlay map
colors = [
    (0,0,0),        # 0 = background
    (255,0,0),      # 1 = red (rectangle)
    (0,255,0),      # 2 = green circle
    (0,0,255),      # 3 = blue square/tree
    (255,255,0)     # 4 = yellow building
]

overlay = orig.convert("RGBA")
ov = Image.new("RGBA", orig.size)
pix = ov.load()

for y in range(pred_np.shape[0]):
    for x in range(pred_np.shape[1]):
        cls = pred_np[y, x]
        r, g, b = colors[cls]
        pix[x, y] = (r, g, b, 90)

overlay = Image.alpha_composite(overlay, ov)

# Bounding boxes
draw = ImageDraw.Draw(overlay)
counts = {}

for cls in [1,2,3,4]:
    ys, xs = np.where(pred_np == cls)
    if len(xs) > 0:
        x1, x2 = xs.min(), xs.max()
        y1, y2 = ys.min(), ys.max()
        draw.rectangle((x1, y1, x2, y2), outline=colors[cls], width=3)
        counts[cls] = 1  # simple object count = 1 per class

# Display results
plt.figure(figsize=(15,5))

plt.subplot(1,3,1)
plt.imshow(orig)
plt.title("Original Image")
plt.axis("off")

plt.subplot(1,3,2)
plt.imshow(pred_big, cmap="nipy_spectral")
plt.title("Segmentation Mask")
plt.axis("off")

plt.subplot(1,3,3)
plt.imshow(overlay)
plt.title("Overlay + Boxes")
plt.axis("off")

plt.show()

print("Object counts:", counts)

import numpy as np
import cv2
from PIL import Image
import matplotlib.pyplot as plt
import os

IMG_DIR = "synthetic_dataset/images"
PRED_DIR = "seg_project/predictions"
OVR_DIR = "seg_project/overlays"

COLOR_MAP = {
    1: (0,255,0),   # green (circles)
    2: (255,0,0),   # blue  (rectangles)
    3: (0,0,255),   # red   (triangles)
    4: (255,255,0), # yellow (extra object if any)
}

def show_full_result(idx, min_area=30):

    idx_str = f"{idx:04d}"

    # Paths
    img_path = f"{IMG_DIR}/{idx_str}.png"
    pred_path = f"{PRED_DIR}/{idx_str}.png"
    overlay_path = f"{OVR_DIR}/{idx_str}.png"

    # Check files exist
    for p in [img_path, pred_path, overlay_path]:
        if not os.path.exists(p):
            print("❌ File missing:", p)
            return

    # Load files
    orig = np.array(Image.open(img_path))
    pred = np.array(Image.open(pred_path))
    overlay = np.array(Image.open(overlay_path))

    # Object detection + box drawing
    boxed = overlay.copy()
    obj_counts = {}

    for cls in [1,2,3,4]:
        mask = (pred == cls).astype("uint8") * 255
        contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

        count = 0
        for cnt in contours:
            if cv2.contourArea(cnt) < min_area:
                continue

            x,y,w,h = cv2.boundingRect(cnt)
            color = COLOR_MAP.get(cls, (255,255,255))
            cv2.rectangle(boxed, (x,y), (x+w,y+h), color, 2)
            count += 1

        if count > 0:
            obj_counts[cls] = count

    # Display results in grid
    fig, ax = plt.subplots(1, 3, figsize=(18,6))

    ax[0].imshow(orig)
    ax[0].set_title("Original Image")
    ax[0].axis("off")

    ax[1].imshow(overlay)
    ax[1].set_title("Segmentation Overlay")
    ax[1].axis("off")

    ax[2].imshow(boxed)
    ax[2].set_title(f"Detected Objects\n{obj_counts}")
    ax[2].axis("off")

    plt.show()

    print("\n=== OBJECT COUNTS ===")
    print(obj_counts)

show_full_result(21)

import shutil
import os

# Make folder if not exists
os.makedirs("extra_test/images", exist_ok=True)

src = "/content/car.png"     # Correct path
dst = "extra_test/images/0000.png"

shutil.copy(src, dst)
print("Copied to:", dst)

import cv2, numpy as np
from PIL import Image
import matplotlib.pyplot as plt
import torch

def unnormalize(t):
    mean = torch.tensor([0.485,0.456,0.406]).view(3,1,1)
    std  = torch.tensor([0.229,0.224,0.225]).view(3,1,1)
    return (t*std + mean).clamp(0,1)

def show_full_result_car():
    IMG_PATH = "/content/car.png"   # uploaded manually
    device = "cuda"

    # Load model
    model = TinyBSCNet(num_classes=5).to(device)
    model.load_state_dict(torch.load("seg_project/checkpoints/best_model.pth", map_location=device))
    model.eval()

    # -------- 1. Load image --------
    orig = Image.open(IMG_PATH).convert("RGB")
    orig_np = np.array(orig)

    # Preprocess (same as training)
    orig_resized = orig.resize((256, 256))
    img = np.array(orig_resized) / 255.0
    img = torch.tensor(img).permute(2,0,1).float()
    img = (img - torch.tensor([0.485,0.456,0.406]).view(3,1,1)) / torch.tensor([0.229,0.224,0.225]).view(3,1,1)
    img = img.unsqueeze(0).to(device)

    # -------- 2. Prediction --------
    with torch.no_grad():
        logits = model(img)
        pred = logits.argmax(dim=1).squeeze().cpu().numpy()

    # -------- 3. Object counting --------
    counts = {}
    for cls in [1,2,3,4]:
        mask = (pred == cls).astype(np.uint8) * 255
        contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        counts[cls] = sum(1 for c in contours if cv2.contourArea(c) > 20)

    # -------- 4. Display results --------
    fig, ax = plt.subplots(1,3, figsize=(18,6))

    ax[0].imshow(orig_np)
    ax[0].set_title("Original Image")
    ax[0].axis('off')

    ax[1].imshow(pred, cmap="tab20")
    ax[1].set_title("Predicted Classes")
    ax[1].axis('off')

    ax[2].imshow(orig_np)
    ax[2].set_title(f"Object Counts: {counts}")
    ax[2].axis('off')

    plt.show()

    print("\n=== DETECTED OBJECTS FROM CAR IMAGE ===")
    print(counts)

show_full_result_car()